<div>
    @if($activity->subactivity->type == 'selling')
        @livewire('frontend.pages.activity.activity-edit.ads-registration.selling', ['activity' => $activity])
    @elseif($activity->subactivity->type == 'employee')
        @livewire('frontend.pages.activity.activity-edit.ads-registration.employment.employee', ['activity' => $activity])
    @elseif($activity->subactivity->type == 'employer')
        @livewire('frontend.pages.activity.activity-edit.ads-registration.employment.employer', ['activity' => $activity])
    @elseif($activity->subactivity->type == 'investor')
        @livewire('frontend.pages.activity.activity-edit.ads-registration.investment.investor', ['activity' => $activity])
    @elseif($activity->subactivity->type == 'invested')
        @livewire('frontend.pages.activity.activity-edit.ads-registration.investment.invested', ['activity' => $activity])
    @elseif($activity->subactivity->type == 'auction')
        @livewire('frontend.pages.activity.activity-edit.ads-registration.bid.auction', ['activity' => $activity])
    @elseif($activity->subactivity->type == 'tender_buy')
        @livewire('frontend.pages.activity.activity-edit.ads-registration.bid.tender.tender_buy', ['activity' => $activity])
    @elseif($activity->subactivity->type == 'tender_project')
        @livewire('frontend.pages.activity.activity-edit.ads-registration.bid.tender.tender_project', ['activity' => $activity])
    @elseif($activity->subactivity->type == 'inquiry_buy')
        @livewire('frontend.pages.activity.activity-edit.ads-registration.inquiry.inquiry_buy', ['activity' => $activity])
    @elseif($activity->subactivity->type == 'inquiry_project')
        @livewire('frontend.pages.activity.activity-edit.ads-registration.inquiry.inquiry_project', ['activity' => $activity])
    @elseif($activity->subactivity->type == 'contractor')
        @livewire('frontend.pages.activity.activity-edit.ads-registration.contractor', ['activity' => $activity])
    @endif
</div>