<div>
    <!-- load steps navigation bar component -->
    @livewire('frontend.pages.private-page.private-page-edit.components.layouts.nav-bar.index')

    <!-- load each section component based on section number -->
    @if($privateSiteSectionNumber == 1)
        @livewire('frontend.pages.private-page.private-page-edit.components.hero.index', ['privateSiteId' => $privateSiteId])
    @elseif($privateSiteSectionNumber == 2)
        @livewire('frontend.pages.private-page.private-page-edit.components.about-us.index', ['privateSiteId' => $privateSiteId])
    @elseif($privateSiteSectionNumber == 3)
        @livewire('frontend.pages.private-page.private-page-edit.components.services.index', ['privateSiteId' => $privateSiteId])
    @elseif($privateSiteSectionNumber == 4)
        @livewire('frontend.pages.private-page.private-page-edit.components.promotional-video.index', ['privateSiteId' => $privateSiteId])
    @elseif($privateSiteSectionNumber == 5)
        @livewire('frontend.pages.private-page.private-page-edit.components.projects.index', ['privateSiteId' => $privateSiteId])
    @elseif($privateSiteSectionNumber == 6)
        @livewire('frontend.pages.private-page.private-page-edit.components.ads.index', ['privateSiteId' => $privateSiteId])
    @elseif($privateSiteSectionNumber == 7)
        @livewire('frontend.pages.private-page.private-page-edit.components.licenses.index', ['privateSiteId' => $privateSiteId])
    @elseif($privateSiteSectionNumber == 8)
        @livewire('frontend.pages.private-page.private-page-edit.components.members.index', ['privateSiteId' => $privateSiteId])
    @elseif($privateSiteSectionNumber == 9)
        @livewire('frontend.pages.private-page.private-page-edit.components.middle-banner.index', ['privateSiteId' => $privateSiteId])
    @elseif($privateSiteSectionNumber == 10)
        @livewire('frontend.pages.private-page.private-page-edit.components.testimonials.index', ['privateSiteId' => $privateSiteId])
    @elseif($privateSiteSectionNumber == 11)
        @livewire('frontend.pages.private-page.private-page-edit.components.blog.index', ['privateSiteId' => $privateSiteId])
    @elseif($privateSiteSectionNumber == 12)
        @livewire('frontend.pages.private-page.private-page-edit.components.trusted-customers.index', ['privateSiteId' => $privateSiteId])
    @elseif($privateSiteSectionNumber == 13)
        @livewire('frontend.pages.private-page.private-page-edit.components.contact-us.index', ['privateSiteId' => $privateSiteId])
    @elseif($privateSiteSectionNumber == 14)
        @livewire('frontend.pages.private-page.private-page-edit.components.footer.index', ['privateSiteId' => $privateSiteId])
    @endif
</div>
